<h4>Terms and Conditions</h4>
<textarea class="form-control" style="height: 150px; border: 1px #ccc solid;">
EVPA is a non-profit organization and does not charge any fees to apply for or to retain membership in the organization. No member of EVPA may request money or charge fees as a prerequisite to offering any assistance or product. In addition, no member is permitted to resell or make any commercial or non-commercial use of the EVPA website or forums. The prohibitions set forth in this paragraph expressly include any and all sales and/or solicitations of money, goods and services no matter for what purpose, person, group or cause, without limitation. Members violating these rules may be subject to immediate membership termination.

EVPA management reserves the right to temporarily suspend or terminate an individual's membership from the organization without notification if certain rules have been violated. The member may appeal the suspension or termination to the Executive Committee, whose decision shall be final. The offending member will have the right to review the written report submitted by the Director of Hub Operations, and provide a written response to management within 30 days.
The general code of conduct reflects on the way EVPA expects members to behave as a member of the organization. Repeated failure to follow the code of conduct may result in a suspension, and eventually termination of the members account.

Members who are new to the hobby or are otherwise unfamiliar with an industry information should well inform themselves by downloading the educational material provided on the EVPA website, joining the forum and asking questions of management, or otherwise researching the information on their own. This is mandatory before representing EVPA on any third party site such as IVAO.

Members should, at all times, be courteous and respectful to one another. Bashing of other members is not permitted. Threatening or harassing any member will result in immediate suspension, and possible termination of the member.

Members represent the EVPA community at all times when visiting other sites on the internet. Members should not undertake any action to bring harm to the reputation of VAC, including, but not limited to misrepresenting yourself to another organization, breaking the rules and guidelines of another organization, or making derogatory statements about EVPA.
</textarea>